# Generated by Django 3.2.5 on 2021-12-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='commentary',
            name='status',
            field=models.CharField(choices=[('d', 'delete_by_admin'), ('a', 'active')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
