# Generated by Django 3.2.5 on 2021-12-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_alter_commentary_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='status',
            field=models.CharField(choices=[('d', 'delete_by_admin')], default=None, max_length=1, null=True),
        ),
    ]
