# Generated by Django 4.0 on 2022-01-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0012_alter_commentary_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='news',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='app_news.News'),
        ),
    ]
