# Generated by Django 4.0 on 2022-01-14 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0014_remove_tag_news_news_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentary',
            options={'verbose_name': 'Commentary', 'verbose_name_plural': 'Commentaries'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['created_at'], 'permissions': (['can_publish', 'может публиковать'],), 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_news.tag'),
        ),
    ]
